ERROR:django.request:Internal Server Error: /prayer/message-detail/2
Traceback (most recent call last):
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'message:'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py", line 45, in message_detail
    return render(request, 'prayer/message_detail.html', context)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\template\engine.py", line 176, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\template\engine.py", line 158, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\template\base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 7: 'message:', expected 'endblock'. Did you forget to register or load this tag?
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
ERROR:django.request:Internal Server Error: /prayer/message-detail/3
Traceback (most recent call last):
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py", line 46, in message_detail
    prayer_groups = logic.queries.PrayerGroupQueries.get_all()
TypeError: PrayerGroupQueries.get_all() missing 1 required positional argument: 'self'
ERROR:django.request:Internal Server Error: /prayer/message-detail/3
Traceback (most recent call last):
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py", line 46, in message_detail
    prayer_groups = logic.queries.PrayerGroupQueries.get_all()
TypeError: PrayerGroupQueries.get_all() missing 1 required positional argument: 'self'
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
ERROR:django.request:Internal Server Error: /prayer/message-detail/3
Traceback (most recent call last):
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py", line 47, in message_detail
    messages = logic.queries.PrayerMessageQueries.get_message_by_id(id=id)
TypeError: PrayerMessageQueries.get_message_by_id() missing 1 required positional argument: 'self'
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
ERROR:django.request:Internal Server Error: /prayer/message-detail/3
Traceback (most recent call last):
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py", line 49, in message_detail
    pg_queries = logic.queires.PrayerGroupQueries()
AttributeError: module 'logic' has no attribute 'queires'
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
ERROR:django.request:Internal Server Error: /prayer/message-detail/3
Traceback (most recent call last):
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py", line 53, in message_detail
    'message': message,
NameError: name 'message' is not defined
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\logic\queries.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
ERROR:django.request:Internal Server Error: /prayer/new-message
Traceback (most recent call last):
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py", line 33, in new_message
    'messages': reverse(PrayerMessage.objects.all())  # TODO move to logic/queries.py
NameError: name 'reverse' is not defined
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
ERROR:django.request:Internal Server Error: /prayer/new-message
Traceback (most recent call last):
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py", line 34, in new_message
    'messages': reversed(msg_query.get_all_messages())  # TODO move to logic/queries.py
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\logic\queries.py", line 153, in get_all_messages
    return PrayerMessage.objects.all(order_by='id')
TypeError: BaseManager.all() got an unexpected keyword argument 'order_by'
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\logic\queries.py changed, reloading.
WARNING:django.security.csrf:Forbidden (CSRF token missing.): /prayer/message-detail/3
WARNING:django.security.csrf:Forbidden (CSRF token missing.): /prayer/message-detail/3
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
ERROR:django.request:Internal Server Error: /prayer/message-detail/3
Traceback (most recent call last):
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'Prayer Chain'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py", line 59, in message_detail
    print(request.POST['Prayer Chain'])
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'Prayer Chain'
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
ERROR:django.request:Internal Server Error: /prayer/message-detail/3
Traceback (most recent call last):
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py", line 59, in message_detail
    print(request.POST.get())
TypeError: MultiValueDict.get() missing 1 required positional argument: 'key'
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
ERROR:django.request:Internal Server Error: /prayer/message-detail/3
Traceback (most recent call last):
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py", line 59, in message_detail
    print(request.POST.data)
AttributeError: 'QueryDict' object has no attribute 'data'
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
ERROR:django.request:Internal Server Error: /prayer/message-detail/3
Traceback (most recent call last):
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py", line 59, in message_detail
    checks = request.POST.getlist('groups').name
AttributeError: 'list' object has no attribute 'name'
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
ERROR:django.request:Internal Server Error: /prayer/message-detail/3
Traceback (most recent call last):
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py", line 63, in message_detail
    for person in group.people:
AttributeError: 'str' object has no attribute 'people'
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
ERROR:django.request:Internal Server Error: /prayer/message-detail/3
Traceback (most recent call last):
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py", line 63, in message_detail
    for person in group_.people:
AttributeError: 'QuerySet' object has no attribute 'people'
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
ERROR:django.request:Internal Server Error: /prayer/message-detail/3
Traceback (most recent call last):
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py", line 62, in message_detail
    group_[0] = pg_queries.get_group_members(group)  # group_ is the object representing the group.
NameError: name 'group_' is not defined
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
ERROR:django.request:Internal Server Error: /prayer/message-detail/3
Traceback (most recent call last):
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py", line 63, in message_detail
    for person in group_.people:
AttributeError: 'Person' object has no attribute 'people'
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
ERROR:django.request:Internal Server Error: /prayer/index
Traceback (most recent call last):
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py", line 21, in index
    'group_members': group_members.get_group_members(group='CBC Members'),
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\logic\queries.py", line 140, in get_group_members
    result = PrayerGroup.objects.get(name=group).people.all()
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\db\models\query.py", line 496, in get
    raise self.model.DoesNotExist(
prayer.models.PrayerGroup.DoesNotExist: PrayerGroup matching query does not exist.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\logic\Messaging\sms.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
INFO:twilio.http_client:-- BEGIN Twilio API Request --
INFO:twilio.http_client:POST Request: https://api.twilio.com/2010-04-01/Accounts/AC34cfca8f7148eeb605137f776419d684/Messages.json
INFO:twilio.http_client:Headers:
INFO:twilio.http_client:User-Agent : twilio-python/7.12.0 (Windows ) Python/3.10.5
INFO:twilio.http_client:X-Twilio-Client : python-7.12.0
INFO:twilio.http_client:Accept-Charset : utf-8
INFO:twilio.http_client:Content-Type : application/x-www-form-urlencoded
INFO:twilio.http_client:Accept : application/json
INFO:twilio.http_client:-- END Twilio API Request --
INFO:twilio.http_client:Response Status Code: 201
INFO:twilio.http_client:Response Headers: {'Date': 'Tue, 16 Aug 2022 19:33:58 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '787', 'Connection': 'keep-alive', 'Twilio-Concurrent-Requests': '1', 'Twilio-Request-Id': 'RQc63899f0d6befeb1a21f91df2c68c25b', 'Twilio-Request-Duration': '0.132', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since', 'Access-Control-Allow-Methods': 'GET, POST, DELETE, OPTIONS', 'Access-Control-Expose-Headers': 'ETag', 'Access-Control-Allow-Credentials': 'true', 'X-Powered-By': 'AT-5000', 'X-Shenanigans': 'none', 'X-Home-Region': 'us1', 'X-API-Domain': 'api.twilio.com', 'Strict-Transport-Security': 'max-age=31536000'}
INFO:twilio.http_client:-- BEGIN Twilio API Request --
INFO:twilio.http_client:POST Request: https://api.twilio.com/2010-04-01/Accounts/AC34cfca8f7148eeb605137f776419d684/Messages.json
INFO:twilio.http_client:Headers:
INFO:twilio.http_client:User-Agent : twilio-python/7.12.0 (Windows ) Python/3.10.5
INFO:twilio.http_client:X-Twilio-Client : python-7.12.0
INFO:twilio.http_client:Accept-Charset : utf-8
INFO:twilio.http_client:Content-Type : application/x-www-form-urlencoded
INFO:twilio.http_client:Accept : application/json
INFO:twilio.http_client:-- END Twilio API Request --
INFO:twilio.http_client:Response Status Code: 201
INFO:twilio.http_client:Response Headers: {'Date': 'Tue, 16 Aug 2022 19:33:58 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '787', 'Connection': 'keep-alive', 'Twilio-Concurrent-Requests': '1', 'Twilio-Request-Id': 'RQab3116bfe2bcd91f9494b608bb3ff323', 'Twilio-Request-Duration': '0.134', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since', 'Access-Control-Allow-Methods': 'GET, POST, DELETE, OPTIONS', 'Access-Control-Expose-Headers': 'ETag', 'Access-Control-Allow-Credentials': 'true', 'X-Powered-By': 'AT-5000', 'X-Shenanigans': 'none', 'X-Home-Region': 'us1', 'X-API-Domain': 'api.twilio.com', 'Strict-Transport-Security': 'max-age=31536000'}
INFO:twilio.http_client:-- BEGIN Twilio API Request --
INFO:twilio.http_client:POST Request: https://api.twilio.com/2010-04-01/Accounts/AC34cfca8f7148eeb605137f776419d684/Messages.json
INFO:twilio.http_client:Headers:
INFO:twilio.http_client:User-Agent : twilio-python/7.12.0 (Windows ) Python/3.10.5
INFO:twilio.http_client:X-Twilio-Client : python-7.12.0
INFO:twilio.http_client:Accept-Charset : utf-8
INFO:twilio.http_client:Content-Type : application/x-www-form-urlencoded
INFO:twilio.http_client:Accept : application/json
INFO:twilio.http_client:-- END Twilio API Request --
INFO:twilio.http_client:Response Status Code: 400
INFO:twilio.http_client:Response Headers: {'Date': 'Tue, 16 Aug 2022 19:33:59 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '147', 'Connection': 'keep-alive', 'Twilio-Request-Id': 'RQ1c05ab4e1e4c4ce3db807b22afc2094a', 'Twilio-Request-Duration': '0.061', 'Twilio-Concurrent-Requests': '1', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since', 'Access-Control-Allow-Methods': 'GET, POST, DELETE, OPTIONS', 'Access-Control-Expose-Headers': 'ETag', 'Access-Control-Allow-Credentials': 'true', 'X-Powered-By': 'AT-5000', 'X-Shenanigans': 'none', 'X-Home-Region': 'us1', 'X-API-Domain': 'api.twilio.com', 'Strict-Transport-Security': 'max-age=31536000'}
ERROR:django.request:Internal Server Error: /prayer/message-detail/3
Traceback (most recent call last):
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py", line 70, in message_detail
    sms_message.send()
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\logic\Messaging\sms.py", line 59, in send
    self._send(message_body=body, phone_number=phone_number)
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\logic\Messaging\sms.py", line 65, in _send
    message = self.client.messages.create(
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\twilio\rest\api\v2010\account\message\__init__.py", line 95, in create
    payload = self._version.create(method='POST', uri=self._uri, data=data, )
  File "C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\venv\lib\site-packages\twilio\base\version.py", line 205, in create
    raise self.exception(method, uri, response, 'Unable to create record')
twilio.base.exceptions.TwilioRestException: HTTP 400 error: Unable to create record: The 'To' number  is not a valid phone number.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\logic\Messaging\sms.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\logic\Messaging\sms.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\logic\Messaging\sms.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\logic\Messaging\sms.py changed, reloading.
INFO:twilio.http_client:-- BEGIN Twilio API Request --
INFO:twilio.http_client:POST Request: https://api.twilio.com/2010-04-01/Accounts/AC34cfca8f7148eeb605137f776419d684/Messages.json
INFO:twilio.http_client:Headers:
INFO:twilio.http_client:User-Agent : twilio-python/7.12.0 (Windows ) Python/3.10.5
INFO:twilio.http_client:X-Twilio-Client : python-7.12.0
INFO:twilio.http_client:Accept-Charset : utf-8
INFO:twilio.http_client:Content-Type : application/x-www-form-urlencoded
INFO:twilio.http_client:Accept : application/json
INFO:twilio.http_client:-- END Twilio API Request --
INFO:twilio.http_client:Response Status Code: 201
INFO:twilio.http_client:Response Headers: {'Date': 'Tue, 16 Aug 2022 19:43:59 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '778', 'Connection': 'keep-alive', 'Twilio-Concurrent-Requests': '1', 'Twilio-Request-Id': 'RQe8f6b841c9bf23428f6804df12664542', 'Twilio-Request-Duration': '0.137', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since', 'Access-Control-Allow-Methods': 'GET, POST, DELETE, OPTIONS', 'Access-Control-Expose-Headers': 'ETag', 'Access-Control-Allow-Credentials': 'true', 'X-Powered-By': 'AT-5000', 'X-Shenanigans': 'none', 'X-Home-Region': 'us1', 'X-API-Domain': 'api.twilio.com', 'Strict-Transport-Security': 'max-age=31536000'}
INFO:twilio.http_client:-- BEGIN Twilio API Request --
INFO:twilio.http_client:POST Request: https://api.twilio.com/2010-04-01/Accounts/AC34cfca8f7148eeb605137f776419d684/Messages.json
INFO:twilio.http_client:Headers:
INFO:twilio.http_client:User-Agent : twilio-python/7.12.0 (Windows ) Python/3.10.5
INFO:twilio.http_client:X-Twilio-Client : python-7.12.0
INFO:twilio.http_client:Accept-Charset : utf-8
INFO:twilio.http_client:Content-Type : application/x-www-form-urlencoded
INFO:twilio.http_client:Accept : application/json
INFO:twilio.http_client:-- END Twilio API Request --
INFO:twilio.http_client:Response Status Code: 201
INFO:twilio.http_client:Response Headers: {'Date': 'Tue, 16 Aug 2022 19:43:59 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '778', 'Connection': 'keep-alive', 'Twilio-Concurrent-Requests': '1', 'Twilio-Request-Id': 'RQ10c0b094d1c751e0d7cf7dfdb5bad3ac', 'Twilio-Request-Duration': '0.151', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since', 'Access-Control-Allow-Methods': 'GET, POST, DELETE, OPTIONS', 'Access-Control-Expose-Headers': 'ETag', 'Access-Control-Allow-Credentials': 'true', 'X-Powered-By': 'AT-5000', 'X-Shenanigans': 'none', 'X-Home-Region': 'us1', 'X-API-Domain': 'api.twilio.com', 'Strict-Transport-Security': 'max-age=31536000'}
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\python_anywhere_website\prayer\views.py changed, reloading.
INFO:twilio.http_client:-- BEGIN Twilio API Request --
INFO:twilio.http_client:POST Request: https://api.twilio.com/2010-04-01/Accounts/AC34cfca8f7148eeb605137f776419d684/Messages.json
INFO:twilio.http_client:Headers:
INFO:twilio.http_client:User-Agent : twilio-python/7.12.0 (Windows ) Python/3.10.5
INFO:twilio.http_client:X-Twilio-Client : python-7.12.0
INFO:twilio.http_client:Accept-Charset : utf-8
INFO:twilio.http_client:Content-Type : application/x-www-form-urlencoded
INFO:twilio.http_client:Accept : application/json
INFO:twilio.http_client:-- END Twilio API Request --
INFO:twilio.http_client:Response Status Code: 201
INFO:twilio.http_client:Response Headers: {'Date': 'Tue, 16 Aug 2022 19:44:38 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '852', 'Connection': 'keep-alive', 'Twilio-Concurrent-Requests': '1', 'Twilio-Request-Id': 'RQfd2017502edd546ff78ef0eb4d35ee2a', 'Twilio-Request-Duration': '0.133', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since', 'Access-Control-Allow-Methods': 'GET, POST, DELETE, OPTIONS', 'Access-Control-Expose-Headers': 'ETag', 'Access-Control-Allow-Credentials': 'true', 'X-Powered-By': 'AT-5000', 'X-Shenanigans': 'none', 'X-Home-Region': 'us1', 'X-API-Domain': 'api.twilio.com', 'Strict-Transport-Security': 'max-age=31536000'}
INFO:twilio.http_client:-- BEGIN Twilio API Request --
INFO:twilio.http_client:POST Request: https://api.twilio.com/2010-04-01/Accounts/AC34cfca8f7148eeb605137f776419d684/Messages.json
INFO:twilio.http_client:Headers:
INFO:twilio.http_client:User-Agent : twilio-python/7.12.0 (Windows ) Python/3.10.5
INFO:twilio.http_client:X-Twilio-Client : python-7.12.0
INFO:twilio.http_client:Accept-Charset : utf-8
INFO:twilio.http_client:Content-Type : application/x-www-form-urlencoded
INFO:twilio.http_client:Accept : application/json
INFO:twilio.http_client:-- END Twilio API Request --
INFO:twilio.http_client:Response Status Code: 201
INFO:twilio.http_client:Response Headers: {'Date': 'Tue, 16 Aug 2022 19:44:38 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '852', 'Connection': 'keep-alive', 'Twilio-Concurrent-Requests': '1', 'Twilio-Request-Id': 'RQdc7c2f45047862760063826abcb09fac', 'Twilio-Request-Duration': '0.169', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since', 'Access-Control-Allow-Methods': 'GET, POST, DELETE, OPTIONS', 'Access-Control-Expose-Headers': 'ETag', 'Access-Control-Allow-Credentials': 'true', 'X-Powered-By': 'AT-5000', 'X-Shenanigans': 'none', 'X-Home-Region': 'us1', 'X-API-Domain': 'api.twilio.com', 'Strict-Transport-Security': 'max-age=31536000'}
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\logic\Messaging\sms.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\logic\Messaging\sms.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\bamah\Documents\VS Code Projects\Python Projects\FS2020\logic\Messaging\sms.py changed, reloading.
